"""Groups chat id

Revision ID: 1d2442aa0a8e
Revises: 19b31bee762c
Create Date: 2026-03-14 20:11:37.624346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2442aa0a8e'
down_revision: Union[str, Sequence[str], None] = '19b31bee762c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('chat_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'chat_id')
    # ### end Alembic commands ###
