"""Except words

Revision ID: 33faffb83319
Revises: af05de4485a8
Create Date: 2026-03-04 23:42:19.803340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '33faffb83319'
down_revision: Union[str, Sequence[str], None] = 'af05de4485a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sub_tariff',
               existing_type=mysql.ENUM('LIGHT', 'MEDIUM', 'HARD', 'ELITE'),
               nullable=True)
    op.alter_column('users', 'is_subscribed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_subscribed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'sub_tariff',
               existing_type=mysql.ENUM('LIGHT', 'MEDIUM', 'HARD', 'ELITE'),
               nullable=False)
    # ### end Alembic commands ###
