"""Except words

Revision ID: 3c29cd8256e3
Revises: 6b8322ea5f0e
Create Date: 2026-03-04 21:05:06.627212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c29cd8256e3'
down_revision: Union[str, Sequence[str], None] = '6b8322ea5f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('except_words', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'except_words')
    # ### end Alembic commands ###
