"""Order keyqords null

Revision ID: 6b8322ea5f0e
Revises: 15ae0bd38a02
Create Date: 2026-03-04 18:17:56.836902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6b8322ea5f0e'
down_revision: Union[str, Sequence[str], None] = '15ae0bd38a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'order_keywords',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'order_keywords',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###
