"""Subscription

Revision ID: cfea01647ef3
Revises: 3c29cd8256e3
Create Date: 2026-03-04 23:35:05.709519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfea01647ef3'
down_revision: Union[str, Sequence[str], None] = '3c29cd8256e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sub_tariff', sa.Enum('LIGHT', 'MEDIUM', 'HARD', 'ELITE', name='subscribetariffenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sub_tariff')
    # ### end Alembic commands ###
