"""Telegram

Revision ID: f938c9c52a2f
Revises: 33faffb83319
Create Date: 2026-03-12 21:51:47.869259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f938c9c52a2f'
down_revision: Union[str, Sequence[str], None] = '33faffb83319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_accounts', sa.Column('telegram_user_id', sa.BigInteger(), nullable=True))
    op.add_column('telegram_accounts', sa.Column('code_hash', sa.String(length=22), nullable=True))
    op.alter_column('telegram_accounts', 'status',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'AUTH_NEEDED', name='telegramaccountstatus'),
               existing_nullable=False)
    op.add_column('users', sa.Column('telegram_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'telegram_accounts', ['telegram_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'telegram_account_id')
    op.alter_column('telegram_accounts', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'AUTH_NEEDED', name='telegramaccountstatus'),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('telegram_accounts', 'code_hash')
    op.drop_column('telegram_accounts', 'telegram_user_id')
    # ### end Alembic commands ###
